In [8]:
import pandas as pd

# HARMONIZED MAPPING CODE FOR KLEBSIELLA PROJECT
# Copy this entire code block into a new cell in your notebook

# Import the harmonized mapping functions
import pandas as pd
import sys
import os
sys.path.append(os.getcwd())  # Add current directory to path
from bac_metadata.pp.metadata_ENA_study import (setup_standardized_columns, debug_sample_matching,
                               map_metadata, display_mapping_results, save_results)

# ===== VARIABLE DEFINITIONS =====
# Study accession
study_accession = "PRJEB1271"

#['PRJEB1271' 'PRJEB5065' 'PRJEB7657' 'PRJEB2111']

# Change for different studies

data_dir = f"/Users/davidabelson/Library/CloudStorage/OneDrive-UniversityofCambridge/Aaron Weimann's files - project_k/data/raw/metadata/study_level_metadata/ENA_projects/{study_accession}"
# Find filesin directory with 'ready_to_merge' in the filename - there should only be one
# Report how many files are found
print(f"Number of files found: {len([f for f in os.listdir(data_dir) if 'ready_to_merge' in f])}")
metadata_file = [f for f in os.listdir(data_dir) if "ready_to_merge" in f][0]
metadata_path = os.path.join(data_dir, metadata_file)
# Print the path
print(f"File path: {metadata_path}")

# Check if the file exists
if os.path.exists(metadata_path):
    print(f"File {metadata_path} exists")
else:
    print(f"File {metadata_path} does not exist")

#project_k_study_dir = f"{data_dir}/ENA_projects/{study_accession}"

# ENA metadata
#Incremental release
#ena_file = f"{data_dir}/ena_metadata_klebsiella_with_header_filtered_r02_format.20240801.tsv"
metadata = pd.read_csv(metadata_path, low_memory=False)  # Added low_memory=False to avoid warnings

Number of files found: 1
File path: /Users/davidabelson/Library/CloudStorage/OneDrive-UniversityofCambridge/Aaron Weimann's files - project_k/data/raw/metadata/study_level_metadata/ENA_projects/PRJEB1271/PRJEB1271_ready_to_merge_with_main_meta_corrected.csv
File /Users/davidabelson/Library/CloudStorage/OneDrive-UniversityofCambridge/Aaron Weimann's files - project_k/data/raw/metadata/study_level_metadata/ENA_projects/PRJEB1271/PRJEB1271_ready_to_merge_with_main_meta_corrected.csv exists

In [9]:
# STEP 2: report on current ENA metadata completeness
metadata_subset = metadata[metadata["study_accession"] == study_accession]
from bac_metadata.pp.metadata_curation import report_ena_data_completeness
report_ena_data_completeness(ena_study_subset, report_columns=True, display_n=3)

The total number of samples in the ENA data file is 221
The total number of study accessions in the ENA data file is 1

After filtering (keeping studies with > 100 unique samples):
  Number of samples: 221
  Number of study accessions: 1

The first 3 study accessions in the ENA data file are: ['PRJEB1271']

Columns completeness summary:

             column  n_filled  n_missing  unique_values
0              host       165         56              1
1           country       165         56              1
2   collection_date       165         56              2
3  isolation_source       164         57              1
4         dev_stage         0        221              0

Detailed column reports:

Column: host
  Present: 165
  Missing: 56
  Unique values (1 total):
    - human: 165

Column: country
  Present: 165
  Missing: 56
  Unique values (1 total):
    - UK: 165

Column: collection_date
  Present: 165
  Missing: 56
  Unique values (2 total):
    - 1800-01-01: 164
    - 1800/2014: 1

Column: isolation_source
  Present: 164
  Missing: 57
  Unique values (1 total):
    - not available: 164

Column: dev_stage
  Present: 0
  Missing: 221
  Unique values (0 total):

(        host country collection_date isolation_source  dev_stage
 8176   human      UK       1800/2014              NaN        NaN
 56943  human      UK      1800-01-01    not available        NaN
 56944  human      UK      1800-01-01    not available        NaN
 56945  human      UK      1800-01-01    not available        NaN
 56946  human      UK      1800-01-01    not available        NaN
 ...      ...     ...             ...              ...        ...
 57617    NaN     NaN             NaN              NaN        NaN
 57618    NaN     NaN             NaN              NaN        NaN
 57619  human      UK      1800-01-01    not available        NaN
 57620    NaN     NaN             NaN              NaN        NaN
 57621  human      UK      1800-01-01    not available        NaN

 [221 rows x 5 columns],
              column  n_filled  n_missing  unique_values
 0              host       165         56              1
 1           country       165         56              1
 2   collection_date       165         56              2
 3  isolation_source       164         57              1
 4         dev_stage         0        221              0)

In [ ]:
# List unique values of country, host and isolation source
print(f"Host values: {metadata_subset["host"].unique()}")
print(f"Country values: {metadata_subset["country"].unique()}")
print(f"Isolation source values: {metadata_subset["isolation_source"].unique()}")
#print(f"Collection date values: {metadata_subset["collection_date"].unique()}")

In [3]:
# Bring in the other samples from ENA data, if the current metadata merge file is not complete
# HARMONIZED MAPPING CODE FOR KLEBSIELLA PROJECT
# Copy this entire code block into a new cell in your notebook

# Import the harmonized mapping functions
import pandas as pd
import sys
import os
sys.path.append(os.getcwd())  # Add current directory to path
from bac_metadata.pp.metadata_ENA_study import (setup_standardized_columns, debug_sample_matching,
                               map_metadata, display_mapping_results, save_results)

# ===== VARIABLE DEFINITIONS =====
# Study accession
study_accession = "PRJEB1271"
all_accessions = [study_accession]
#other_study_accession = "PRJEB50614"
#all_accessions = [study_accession, other_study_accession]

# Change for different studies
data_dir = "/Users/davidabelson/Library/CloudStorage/OneDrive-UniversityofCambridge/Aaron Weimann's files - project_k/data/raw/metadata"
project_k_study_dir = f"{data_dir}/study_level_metadata/ENA_projects/{study_accession}"

# ===== STEP 2: ENA DATA ON PROJECT NUMBER =====
# This section loads the ENA metadata and prepares it for updating

# STEP 2.1: Load the ENA metadata file
#Initial data release
ena_file = f"{data_dir}/ena_metadata_klebsiella_with_header_filtered.tsv"
ena_data_initial = pd.read_csv(ena_file, sep="\t", low_memory=False)  # Added low_memory=False to avoid warnings
#Incremental release
ena_file = f"{data_dir}/ena_metadata_klebsiella_with_header_filtered_r02_format.20240801.tsv"
ena_data_incremental = pd.read_csv(ena_file, sep="\t", low_memory=False)  # Added low_memory=False to avoid warnings

# Append together the incremental and initial data releases
ena_data = pd.concat([ena_data_initial, ena_data_incremental])    

# STEP 2: report on current ENA metadata completeness
# Match using both study_accession and other_study_accession values in the same column

ena_study_subset = ena_data[ena_data["study_accession"].isin(all_accessions)]
from bac_metadata.pp.metadata_curation import report_ena_data_completeness
report_ena_data_completeness(ena_study_subset, report_columns=True, display_n=3)

The total number of samples in the ENA data file is 221
The total number of study accessions in the ENA data file is 1

After filtering (keeping studies with > 100 unique samples):
  Number of samples: 221
  Number of study accessions: 1

The first 3 study accessions in the ENA data file are: ['PRJEB1271']

Columns completeness summary:

             column  n_filled  n_missing  unique_values
0              host       165         56              1
1           country       165         56              1
2   collection_date       165         56              2
3  isolation_source       164         57              1
4         dev_stage         0        221              0

Detailed column reports:

Column: host
  Present: 165
  Missing: 56
  Unique values (1 total):
    - human: 165

Column: country
  Present: 165
  Missing: 56
  Unique values (1 total):
    - UK: 165

Column: collection_date
  Present: 165
  Missing: 56
  Unique values (2 total):
    - 1800-01-01: 164
    - 1800/2014: 1

Column: isolation_source
  Present: 164
  Missing: 57
  Unique values (1 total):
    - not available: 164

Column: dev_stage
  Present: 0
  Missing: 221
  Unique values (0 total):

(        host country collection_date isolation_source  dev_stage
 8176   human      UK       1800/2014              NaN        NaN
 56943  human      UK      1800-01-01    not available        NaN
 56944  human      UK      1800-01-01    not available        NaN
 56945  human      UK      1800-01-01    not available        NaN
 56946  human      UK      1800-01-01    not available        NaN
 ...      ...     ...             ...              ...        ...
 57617    NaN     NaN             NaN              NaN        NaN
 57618    NaN     NaN             NaN              NaN        NaN
 57619  human      UK      1800-01-01    not available        NaN
 57620    NaN     NaN             NaN              NaN        NaN
 57621  human      UK      1800-01-01    not available        NaN

 [221 rows x 5 columns],
              column  n_filled  n_missing  unique_values
 0              host       165         56              1
 1           country       165         56              1
 2   collection_date       165         56              2
 3  isolation_source       164         57              1
 4         dev_stage         0        221              0)

In [ ]:
# Manual curation of corrected metadata if current entry is null
metadata_subset.loc[:, "host"] = "Human"
metadata_subset.loc[:, "isolation_source"] = "blood"
metadata_subset.loc[:, "dev_stage"] = "newborn"
#metadata_subset.loc[:, "country"] = "United Kingdom: Wales"
#metadata_subset.loc[metadata_subset["host"]=="env", "host"] = "Clinical environment"
#metadata_subset.loc[metadata_subset["country"].isna(), "country"] = "Philippines"
#metadata_subset.loc[metadata_subset["isolation_source"] == "Other", "isolation_source"] = pd.NA
#metadata_subset.loc[metadata_subset["isolation_source"] == "nan", "isolation_source"] = pd.NA

In [ ]:
print(metadata_subset["country"].unique())
print(metadata_subset["host"].unique())
print(metadata_subset["isolation_source"].unique())

In [ ]:
# Save the corrected metadata back over original file
metadata_subset.to_csv(metadata_path)